forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-stdlib'
mod 'junglecatsoftware-nodetype',
  :path => '../puppet-nodetype'
mod 'junglecatsoftware-webproxy',
  :path => '../puppet-webproxy'
mod 'jfryman-nginx', '0.2.7'
