forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-stdlib'
#mod 'junglecatsoftware-jcsprofiles'
#  :path => 'puppetmodules/puppet-jscprofiles'
#mod 'junglecatsoftware-jcsroles'
#  :path => 'puppetmodules/puppet-jscroles'
