mod 'junglecatsoftware/nodetype', :local => true
mod 'junglecatsoftware/webproxy', :local => true
mod 'junglecatsoftware/authservices', :local => true
mod 'puppetlabs/stdlib', :latest
mod 'jfryman/nginx', '0.2.7'
mod 'stankevich/python', '1.10.0'
